### ISSUE TITLE
toggling

### ISSUE THREAD

**Issue by josefstr** [Drauthius/awesome-sharedtags#1]
You're writing that some toggling is not working on multiple screens.
I just wanted to ask if this is the expected behaviour.
I have two monitors connected. On the primary monitor everything is working as expected but when I try to run
`-- View tag only.
         awful.key({ modkey }, "#" .. i + 9,
                   function ()
                         local tag = tags[i]
                         if tag then
                            sharedtags.viewonly(tag)
                         end
                   end),`

For example if I run modkey + 1 on first workspace on secondary monitor, it moves my first workspace from the primary monitor to the secondary screen and puts it in front of the first workspace of my secondary monitor.

`
         -- Move client to tag.
         awful.key({ modkey, "Shift" }, "#" .. i + 9,
                   function ()
                       if client.focus then
                           local tag = tags[i]
                           if tag then
                               awful.client.movetotag(tag)
                           end
                      end
                   end),
`
Running this on my secondary monitor the program get's moved to the corresponding workspace on the primary monitor.

**Comment by Drauthius** [comment]
The note in the readme refers to `awful.client.toggletag(tag)` (default `modkey + control + shift + #`), which shares a client (program) on multiple tags (workspaces). It is not possible to have the same program be drawn on multiple monitors.

The toggling you're explaining is working as expected. Each workspace is unique, and can only be on one monitor at a time. So pressing `modkey + 1` activates the first workspace, and moves it to the monitor where the mouse is. The workspaces in the bar are sorted by their number.
