### ISSUE TITLE
The tag is not displayed on the correct screen after the computer start up

### ISSUE THREAD

**Issue by xvrong** [Drauthius/awesome-sharedtags#10]
Hello, I have a problem and need help. I have two screens, and the screen set for the tag does not work when I boot up, all the tags are displayed on one of my screens, however, after running awesome.restart the tags move to the correct screen, I have this problem with both awesome's stable and git versions.

**Comment by Drauthius** [comment]
Hi. Have you configured the screen index when creating the tags as in the example? The screen number starts from 1 and up. I've had no problems with that and Awesome 4.3.

If for some reason your screens aren't all registered to Awesome at start you could move tags programmatically in `awful.screen.connect_for_each_screen`, e.g.:
```lua
awful.screen.connect_for_each_screen(function(s)
    if s.index == 2 then
        sharedtags.viewonly(tags[2], s)
    end
end)
```

**Comment by xvrong** [comment]
Thank you for your reply. My problem has been solved. It seems that my screens aren't all registered to Awesome.
Before, I wrote the xrandr command into the configuration file of Awesome. Now, I write the xrandr command into xinit and execute it before the startup of Awesome. All the tags appear on the correct screen.
