### ISSUE TITLE
attempt to index local 'oldscreen' (a nil value)

### ISSUE THREAD

**Issue by teranex** [Drauthius/awesome-sharedtags#2]
awesome v4.1 (Technologic)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

sharedtags running from commit 54f5929fc5d267ea53fc049b273e0d3bc6b6c104

Full config: https://github.com/teranex/awesome-config/tree/awesome-4.0

Steps to reproduce:
* I use the following tags: [1,2,3,4,5,6,7,8,9,0,-,=].
* When I attach a second screen, I move tags 0, -, = to the second monitor, 1,2,3,4,5,6,7,8,9 remain on the primary screen.
* Then I unplug the second screen
* When I try to switch to one of the tags that were on the second screen, 0,-,=, I get "attempt to index local 'oldscreen' (a nil value)"
* When I re-attach the screen and try to switch to one of the tags from the second screen I get the same error.
* Restarting Awesome makes the tags accessible again

```
2017-04-01 23:15:23 W: awesome: luaA_dofunction:77: error while running function!
stack traceback:
	/home/jeroen/.config/awesome/sharedtags/init.lua:92: in function 'movetag'
	/home/jeroen/.config/awesome/sharedtags/init.lua:131: in function 'viewonly'
	/home/jeroen/.config/awesome/rc.lua:492: in function 'press'
	/usr/local/share/awesome/lib/awful/key.lua:91: in function </usr/local/share/awesome/lib/awful/key.lua:91>
error: /home/jeroen/.config/awesome/sharedtags/init.lua:92: attempt to index local 'oldscreen' (a nil value)
```

**Comment by Drauthius** [comment]
Thanks for the detailed bug report. Your problem should be fixed in the latest commit.

**Comment by teranex** [comment]
I just tested this commits and it works perfectly. Thanks a lot!
