### ISSUE TITLE
Provide example of "dynamic" tag creation/deletion

### ISSUE THREAD

**Issue by pinpox** [Drauthius/awesome-sharedtags#6]
You mention "dynamic tag adding" in the comment here:

https://github.com/Drauthius/awesome-sharedtags/blob/32d878d0d12bcfd900f2c6a7516a1370e6ebb7d6/init.lua#L57

How would I implement this correctly? I would like to delete empty, non-visible tags and create new tags dynamically on the current screen when switching to them if they don't yet exists.

**Comment by Drauthius** [comment]
In the place you handle the keybindings, you would need to call `sharedtags.add(i, t)`, where `i` is an index (for example the key that was pressed), and `t` is a table containing a definition, same as the one given to `sharedtags()`, but only one entry (for example `sharedtags.add(i, { name = i, screen = screen })`. This will create a new tag for the given index, which you would need to store somewhere (for example in `tags[i]`). How you manage or keep track of tags is mostly up to you. You could for example check if `tags[i]` is set, and if not create the tag and store it, followed by switching to it with `shardetags.viewonly`.

I'm not sure what you mean by non-visible tags. For empty tags, see the [official documentation](https://awesomewm.org/doc/api/classes/tag.html#). Running programs are called clients in Awesome, so you could for example check whether `next(tags[i]:clients())` returns a result.

If you could describe more closely what you're having problems with, I could try and explain further.
