### ISSUE TITLE
Provide example for "move tag to another screen"

### ISSUE THREAD

**Issue by avanc** [Drauthius/awesome-sharedtags#7]
I'm struggling to implementing a shortcut for moving one tag to another screen. tag.setscreen seems to be deprecated.

**Comment by avanc** [comment]
I'm struggeling in getting the next screen:

```
local curr_screen = awful.screen.focused()
local curr_tag = curr_screen.selected_tag
local new_screen = ???
sharedtags.movetag(curr_tag, new_screen)

```

**Comment by Drauthius** [comment]
You'd need to plug in the screen object you want the tag to go to. See https://awesomewm.org/doc/api/classes/screen.html for some functions that you can use on `curr_screen`, e.g. `get_next_in_direction()` or just `screen()` to iterate over all available screens to find the one you are interested in. Alternatively, you could save the screen object from `awful.screen.connect_for_each_screen()` in a variable and pass that on later.

**Comment by avanc** [comment]
Thanks for the hint. However, nothing happens with the following code:

```
awful.key({ modkey }, "less", function ()
                                    local curr_screen = awful.screen.focused()
                                    local curr_tag = curr_screen.selected_tag
                                    local new_screen = curr_screen.get_next_in_direction()
                                    sharedtags.movetag(curr_tag, new_screen)
                                  end,
            {description = "Move tag to next screen", group = "tag"})

```

**Comment by Drauthius** [comment]
The command should be `local new_screen = curr_screen:get_next_in_direction("left")`, replacing "left" with "right", "up", or "down". 

If you are instead interested in just sending the tag to the other screen regardless of direction, use the following.
```lua
local new_screen
for s in screen do
    if s ~= curr_screen then
        new_screen = s
        break
    end
end
```

**Comment by avanc** [comment]
@Drauthius Thanks, that helped. I have chosen the second approach.
In addition, I just realized that Tags are moved to the active screen, if `<Super> + <Number>` is hit.

**Comment by Drauthius** [comment]
@avanc I don't understand what you mean by if + is hit. Did you bind something to +?

**Comment by avanc** [comment]
Sorry, I didn't saw that the formatting of my comment was broken. I fixed it.

I just meant that if I activate a tag on another screen where the tag is bound, the tag with its client are moved to the active screen.

**Comment by avanc** [comment]
However, I still struggle while disconnecting a screen:
Screen A contains tag 1, 2, and 3
Screen B contains tag 4, 5, 6
Disconnecting screen B (e.g. xrandr), tags 4, 5, 6 are lost and the clients are moved to the active tag. To what signal do I have to listen to move those tags to the existing screen A before the screen B is gone?

**Comment by Drauthius** [comment]
That scenario should be taken care of the plugin automatically. With awesome 4.3, my tags are all moved to the remaining screen when I disconnect a screen with xrandr. What version of awesome are you running?

**Comment by Mange** [comment]
I also have an issue with tags disappearing if I disconnect screens.

```
› awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by Drauthius** [comment]
Try the latest commit to see if it fixes the issue with tags staying on disconnected screens. I've seen the problem myself a few times, but not been able to reproduce it now.

**Comment by avanc** [comment]
@Drauthius Thanks, this fix works!
